name: jverify
description: JIGUANG Official Jverifycation SDK flutter plugin project.
version: 3.0.0
homepage: https://www.jiguang.cn

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.jiguang.jverify
        pluginClass: JverifyPlugin
      ios:
        pluginClass: JverifyPlugin
